### ISSUE TITLE
动态抽奖报错

### ISSUE THREAD

**Issue by L1cardo** [InJeCTrL/BiliCLOnline#15]
```bash
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:63003
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\B站抽奖
fail: BiliCLOnline.Utils.WebHelper[0]
      Exception: [System.Net.Http.HttpRequestException: https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?id=973263946104438800
         at BiliCLOnline.Utils.WebHelper.GetResponse[T](String URL, String cookie)] url: [https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?id=973263946104438800]
fail: BiliCLOnline.Utils.WebHelper[0]
      Exception: [System.Net.Http.HttpRequestException: https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?id=973263946104438800
         at BiliCLOnline.Utils.WebHelper.GetResponse[T](String URL, String cookie)] url: [https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?id=973263946104438800]
fail: BiliCLOnline.Utils.WebHelper[0]
      Exception: [System.Net.Http.HttpRequestException: https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?id=973263946104438800
         at BiliCLOnline.Utils.WebHelper.GetResponse[T](String URL, String cookie)] url: [https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?id=973263946104438800]
fail: BiliCLOnline.Utils.WebHelper[0]
      Exception: [System.Net.Http.HttpRequestException: https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?id=973263946104438800
         at BiliCLOnline.Utils.WebHelper.GetResponse[T](String URL, String cookie)] url: [https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?id=973263946104438800]
fail: BiliCLOnline.Utils.WebHelper[0]
      Exception: [System.Net.Http.HttpRequestException: https://api.bilibili.com/x/v2/reply/main?mode=2&oid=973263946104438800&type=17&ps=30&next=
         at BiliCLOnline.Utils.WebHelper.GetResponse[T](String URL, String cookie)] url: [https://api.bilibili.com/x/v2/reply/main?mode=2&oid=973263946104438800&type=17&ps=30&next=]
fail: BiliCLOnline.Utils.WebHelper[0]
      Exception: [System.Net.Http.HttpRequestException: https://api.bilibili.com/x/v2/reply/main?mode=2&oid=973263946104438800&type=17&ps=30&next=
         at BiliCLOnline.Utils.WebHelper.GetResponse[T](String URL, String cookie)] url: [https://api.bilibili.com/x/v2/reply/main?mode=2&oid=973263946104438800&type=17&ps=30&next=]
fail: BiliCLOnline.Utils.WebHelper[0]
      Exception: [System.Net.Http.HttpRequestException: https://api.bilibili.com/x/v2/reply/main?mode=2&oid=973263946104438800&type=17&ps=30&next=
         at BiliCLOnline.Utils.WebHelper.GetResponse[T](String URL, String cookie)] url: [https://api.bilibili.com/x/v2/reply/main?mode=2&oid=973263946104438800&type=17&ps=30&next=]
fail: BiliCLOnline.Utils.WebHelper[0]
      Exception: [System.Net.Http.HttpRequestException: https://api.bilibili.com/x/v2/reply/main?mode=2&oid=973263946104438800&type=17&ps=30&next=
         at BiliCLOnline.Utils.WebHelper.GetResponse[T](String URL, String cookie)] url: [https://api.bilibili.com/x/v2/reply/main?mode=2&oid=973263946104438800&type=17&ps=30&next=]
fail: BiliCLOnline.Utils.WebHelper[0]
      Exception: [System.Net.Http.HttpRequestException: https://api.bilibili.com/x/v2/reply/main?mode=2&oid=973263946104438800&type=17&ps=30&next=
         at BiliCLOnline.Utils.WebHelper.GetResponse[T](String URL, String cookie)] url: [https://api.bilibili.com/x/v2/reply/main?mode=2&oid=973263946104438800&type=17&ps=30&next=]
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN6DHO9AKRU1", Request id "0HN6DHO9AKRU1:00000008": An unhandled exception was thrown by the application.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at BiliCLOnline.Services.ReplyResult.InvokeGetListTask(String formalId, String cookie)
         at BiliCLOnline.Controllers.ReplyController.ExecuteFetchReplyResult(String id, String cookie)
         at lambda_method29(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint, Task, ILogger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1)
```

**Comment by InJeCTrL** [comment]
Hi @L1cardo , 您要抽奖的是否是这个视频，可以直接用视频url发起抽奖： https://www.bilibili.com/video/BV18tpFePEZM

**Comment by InJeCTrL** [comment]
现在可以切换到使用BiliCLMonkey更快速高效
https://github.com/InJeCTrL/BiliCLMonkey

**Comment by L1cardo** [comment]
ok， 感谢
